OC\PlatformBundle\Entity\Coefficient:
    type: entity
    table: coefficient
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dept:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        statut:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
        coef:
            type: float
            nullable: false
            precision: 18
            scale: 2
    lifecycleCallbacks: {  }
