OC\PlatformBundle\Entity\Ingroup:
    type: entity
    table: ingroup
    indexes:
        etudiant_id_idx:
            columns:
                - etudiant_id
        groupe_id_idx:
            columns:
                - groupe_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        start:
            type: date
            nullable: true
        end:
            type: date
            nullable: true
        groupeId:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: groupe_id
    manyToOne:
        etudiant:
            targetEntity: Etudiant
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                etudiant_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
