OC\PlatformBundle\Entity\Planning:
    type: entity
    table: planning
    indexes:
        teacher_id_idx:
            columns:
                - teacher_id
        course_id_idx:
            columns:
                - course_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cm:
            type: float
            nullable: true
            precision: 18
            scale: 2
        td:
            type: float
            nullable: true
            precision: 18
            scale: 2
        tp:
            type: float
            nullable: true
            precision: 18
            scale: 2
    manyToOne:
        course:
            targetEntity: Course
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                course_id:
                    referencedColumnName: id
            orphanRemoval: false
        teacher:
            targetEntity: Teacher
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                teacher_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
