OC\PlatformBundle\Entity\Room:
    type: entity
    table: room
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        dept:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
    lifecycleCallbacks: {  }
