OC\PlatformBundle\Entity\SfGuardForgotPassword:
    type: entity
    table: sf_guard_forgot_password
    indexes:
        user_id_idx:
            columns:
                - user_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uniqueKey:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: unique_key
        expiresAt:
            type: datetime
            nullable: false
            column: expires_at
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        user:
            targetEntity: SfGuardUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
