OC\PlatformBundle\Entity\SfGuardRememberKey:
    type: entity
    table: sf_guard_remember_key
    indexes:
        user_id_idx:
            columns:
                - user_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rememberKey:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: remember_key
        ipAddress:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ip_address
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        user:
            targetEntity: SfGuardUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
