OC\PlatformBundle\Entity\Subject:
    type: entity
    table: subject
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        shortname:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        cnu:
            type: bigint
            nullable: false
            options:
                unsigned: false
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
