OC\PlatformBundle\Entity\Weekcomment:
    type: entity
    table: weekcomment
    indexes:
        teacher_id_idx:
            columns:
                - teacher_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dept:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        comment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        week:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        teacher:
            targetEntity: Teacher
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                teacher_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
